name: build-poetry
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '35 21 * * 1'  # 9:35pm UTC each Monday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  # yes, this is not DRY, but it keeps all the "config" in this one place
  IMAGE: ghcr.io/${{ github.repository_owner }}/poetry
  IMAGE_NAME: poetry
  REGISTRY: ghcr.io

jobs:
  get-versions:
    name: Get poetry version
    runs-on: ubuntu-latest
    outputs:
      poetry: ${{ steps.poetry.outputs.version }}
    steps:
      - name: Fetch poetry versions
        run: curl "https://release-monitoring.org/api/v2/versions/?project_id=32514" -o poetry.json
      - name: Get poetry version
        id: poetry
        run: echo "version=$(jq -r '.stable_versions[0]' poetry.json)" >> $GITHUB_OUTPUT

  build-image:
    name: Build image (${{ matrix.poetry }}, ${{ matrix.variant }}, ${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    needs: get-versions
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
        poetry:
          - ${{ needs.get-versions.outputs.poetry }}
        python:
          - "3.11"
        variant:
          - "git"
          - "extras"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ env.IMAGE }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=A containerized python poetry image with ${{ matrix.variant }}
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
          tags: |
            type=sha,format=short,suffix=-${{ matrix.variant }}-${{ matrix.arch }}

      - name: Build Image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          build-args: |
            POETRY_VERSION=${{ matrix.poetry }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=${{ matrix.variant }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: false

      - name: Push image to registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          extra-args: |
            --disable-content-trust

  combine-manifest:
    name: Combine manifests (${{ matrix.poetry }}, ${{ matrix.variant }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: [get-versions, build-image]
    strategy:
      fail-fast: false
      matrix:
        poetry:
          - ${{ needs.get-versions.outputs.poetry }}
        variant:
          - "git"
          - "extras"
    steps:
      - name: Get timestamp
        id: timestamp
        run: echo "ts=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Manifest Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          tags: |
            # PR tags
            type=ref,event=pr,suffix=-${{ matrix.variant }}
            # SHA tag (short)
            type=sha,format=short,suffix=-${{ matrix.variant }}
            # Only add these tags if it's a push to main or workflow_dispatch on main
            # VARIANT, POETRYVERSION-VARIANT, POETRYVERSION-VARIANT-TIMESTAMP
            ${{ ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main') && format('type=raw,value={0}\ntype=raw,value={1}-{0}\ntype=raw,value={1}-{0}-{2}', matrix.variant, matrix.poetry, steps.timestamp.outputs.ts) || '' }}

      - name: Login to registry
        run: podman login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifests for all tags
        shell: bash
        run: |
          set -e
          IMAGE=${{ env.IMAGE }}
          BUILD_TAG=sha-${GITHUB_SHA::7}-${{ matrix.variant }}

          echo "IMAGE=$IMAGE"
          echo "BUILD_TAG=$BUILD_TAG"
          echo "TAGS=${{ steps.meta.outputs.tags }}"

          IFS=',' read -ra TAGS <<< "${{ steps.meta.outputs.tags }}"
          # each tag gets its own manifest
          for tag in "${TAGS[@]}"; do
            echo "Creating and pushing manifest for $tag"
            podman manifest create $IMAGE:$tag

            # Add both arch images (built by previous jobs)
            podman manifest add $IMAGE:$tag docker://$IMAGE:${BUILD_TAG}-amd64
            podman manifest add $IMAGE:$tag docker://$IMAGE:${BUILD_TAG}-arm64

            # Push the manifest to registry
            podman manifest push --all $IMAGE:$tag docker://$IMAGE:$tag
          done

      # Install Cosign
      - uses: sigstore/cosign-installer@v3.0.2

      - name: Sign multi-arch manifest with Cosign
        if: github.event_name != 'pull_request'
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'); do
            cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.IMAGE }}:$tag
          done
